### ISSUE TITLE
What happened to the repo?

### ISSUE THREAD

**Issue by TheZ3ro** [MatrixEditor/pysmali#4]
Hello,
What happened to the repository? All the commit history, the issues and the PR got deleted.
:(

**Comment by MatrixEditor** [comment]
Unfortunately I had to clean up the Commit-History and re-create all my repositories. Far more worse is that this one here is the only repo where the old issues weren't transferred. *PRs can't be transferred.

I could manually add a contributed-list in the main README, if you like.

**Comment by TheZ3ro** [comment]
That would be awesome!

**Comment by MatrixEditor** [comment]
Fixed with latest commit [89cf84634dd704cf12eecea7989586b455996fd3](https://github.com/MatrixEditor/pysmali/commit/89cf84634dd704cf12eecea7989586b455996fd3)
