### ISSUE TITLE
SVMType.pretty_name bug

### ISSUE THREAD

**Issue by iladrien-hub** [MatrixEditor/pysmali#5]
On this line: https://github.com/MatrixEditor/pysmali/blob/master/smali/base.py#L628 absolutely all characters `L` are deleted...

What about classes whose names contain a capital L? E.g.:

- LoadBalancer
- LifeCycleManager
- LevelTracker
- LineParser
- LogManager

**Comment by MatrixEditor** [comment]
Hey @iladrien-hub, thanks for reporting that issue - I totally missed that. Feel free to create pull requests, otherwise the patch has to wait until I have some time left.
